version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    privileged: true
    devices:
      - "COM4:COM4"
    environment:
      - TZ=Europe/Moscow
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
#    expose:
#      - COM5
    cap_add:
      - ALL
#    security_opt:
#      - seccomp=unconfined