version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /dev:/dev
    ports:
      - "8000:8000"
    privileged: true
    devices:
      - "/dev/tty:/dev/tty"
      - "/dev/tty0:/dev/tty0"
      - "/dev/tty1:/dev/tty1"
      - "/dev/tty2:/dev/tty2"
      - "/dev/tty3:/dev/tty3"
      - "/dev/tty4:/dev/tty4"
      - "/dev/tty5:/dev/tty5"
      - "/dev/tty6:/dev/tty6"
      - "/dev/tty7:/dev/tty7"
      - "/dev/tty8:/dev/tty8"
      - "/dev/tty9:/dev/tty9"
      - "/dev/tty10:/dev/tty10"
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyS1:/dev/ttyS1"
      - "/dev/ttyS2:/dev/ttyS2"
      - "/dev/ttyS3:/dev/ttyS3"
    environment:
      - TZ=Europe/Moscow
    restart: always
#    expose:
#      - COM5
    cap_add:
      - ALL
#    security_opt:
#      - seccomp=unconfined