# Generated by Django 3.2.5 on 2021-07-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartHouseApp', '0003_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('can_set_light', 'can_set_temperature'),)},
        ),
    ]
