# Generated by Django 3.2.5 on 2021-07-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartHouseApp', '0005_rename_users_smarthouseuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smarthouseuser',
            options={'permissions': [('can_set_temperature', 'Can set temperature')]},
        ),
    ]
